### ISSUE TITLE
Non-cumulable nodes should display - rather than 0 as the cumulative effect

### ISSUE THREAD

**Issue by jtuomist** [kausaltech/kausal-paths-ui#18]
For example district_heating_emission_factor shows 0 g/kWh as the total impact 2018-2030. It is not meaningful to integrate this node over time, so it should display "-" rather than "0 g/kWh" as the cumulative effect.

**Comment by terotik** [comment]
This is duck taped now by showing cumulative only on emission type nodes, need backend solution if we want to show cumulative on any other types (ie. consumption)

**Comment by terotik** [comment]
Fixed ce1172150c9ca0a8760756b7a0a1d9e175a5d27b
